import localFont from "next/font/local";
import "./globals.css";
import TopNavBar from "./components/top_nav";

const manbow = localFont({
  src: "./fonts/manbow.otf",
  variable: "--font-manbow",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manbow.variable} antialiased`}
      >
        <TopNavBar />
        {children}
      </body>
    </html>
  );
}
